[deploy]
startCommand = "python manage.py migrate && python seed_data.py && gunicorn portfolio_project.wsgi:application"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --no-input"
